# **1Ô∏è‚É£ Import Libraries**

In [257]:
import pandas as pd
import numpy as np

# **2Ô∏è‚É£ Load Dataset**

In [258]:
# üìÇ Load raw dataset
df = pd.read_csv('/content/Car Sales.csv')

# Preview dataset
df.sample(5)

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
3994,C_CND_003995,7/16/2022,Tiana,Female,310000,Progressive Shippers Cooperative Association No,Toyota,4Runner,Overhead Camshaft,Manual,Black,25001,53546-9427,Sedan,6022289,Janesville
22450,C_CND_022451,12/6/2023,Rafael,Male,510000,Chrysler of Tri-Cities,Mitsubishi,Montero,Overhead Camshaft,Manual,Black,16000,99301-3882,SUV,8734769,Pasco
919,C_CND_000920,3/14/2022,Vincent,Male,1385000,Star Enterprises Inc,Lexus,LX470,Double√Ç¬†Overhead Camshaft,Auto,Black,22500,99301-3882,SUV,7864153,Greenville
5836,C_CND_005837,9/17/2022,Heidy,Male,13500,Ryder Truck Rental and Leasing,Ford,Escort,Overhead Camshaft,Manual,Black,11000,06457-3834,Passenger,8512115,Middletown
14714,C_CND_014715,6/12/2023,Jimmy,Male,1460000,Race Car Help,Lexus,LX470,Double√Ç¬†Overhead Camshaft,Auto,Black,22000,78758-7841,SUV,6348275,Austin

# **3Ô∏è‚É£ Explore Dataset**

In [259]:
# Shape of dataset
df.shape

(23906, 16)

In [260]:
# üîç Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_id         23906 non-null  object
 1   Date           23906 non-null  object
 2   Customer Name  23905 non-null  object
 3   Gender         23906 non-null  object
 4   Annual Income  23906 non-null  int64
 5   Dealer_Name    23906 non-null  object
 6   Company        23906 non-null  object
 7   Model          23906 non-null  object
 8   Engine         23906 non-null  object
 9   Transmission   23906 non-null  object
 10  Color          23906 non-null  object
 11  Price ($)      23906 non-null  int64
 12  Dealer_No      23906 non-null  object
 13  Body Style     23906 non-null  object
 14  Phone          23906 non-null  int64
 15  Dealer_Region  23906 non-null  object
dtypes: int64(3), object(13)
memory usage: 2.9+ MB

In [261]:
# üìä Statistical Summary
df.describe()

       Annual Income     Price ($)         Phone
count   2.390600e+04  23906.000000  2.390600e+04
mean    8.308403e+05  28090.247846  7.497741e+06
std     7.200064e+05  14788.687608  8.674920e+05
min     1.008000e+04   1200.000000  6.000101e+06
25%     3.860000e+05  18001.000000  6.746495e+06
50%     7.350000e+05  23000.000000  7.496198e+06
75%     1.175750e+06  34000.000000  8.248146e+06
max     1.120000e+07  85800.000000  8.999579e+06

In [262]:
# üß© Check Missing Values
df.isnull().sum()

Car_id           0
Date             0
Customer Name    1
Gender           0
Annual Income    0
Dealer_Name      0
Company          0
Model            0
Engine           0
Transmission     0
Color            0
Price ($)        0
Dealer_No        0
Body Style       0
Phone            0
Dealer_Region    0
dtype: int64

# **4Ô∏è‚É£ Data Cleaning & Transformation**

In [263]:
# ‚úèÔ∏è Rename Columns for Readability
df = df.rename(columns={
    'Annual Income'  : 'Annul_Income',
    'Body Style' : 'Body_Style	',
    'Dealer_No ' : 'Dealer_No',
    'Price ($)' : 'Price'
})

In [264]:
# üóëÔ∏è Drop Unnecessary Columns
df = df.drop(['Engine', 'Dealer_No', 'Customer Name', 'Phone', 'Dealer_Name'], axis=1)

In [265]:
# üßπ Drop Missing Values
df = df.dropna()

In [266]:
# üìÜ Convert Order_date to DateTime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [267]:
df

,Car_id,Date,Gender,Annul_Income,Company,Model,Transmission,Color,Price,Body_Style\t,Dealer_Region
0,C_CND_000001,2022-01-02,Male,13500,Ford,Expedition,Auto,Black,26000,SUV,Middletown
1,C_CND_000002,2022-01-02,Male,1480000,Dodge,Durango,Auto,Black,19000,SUV,Aurora
2,C_CND_000003,2022-01-02,Male,1035000,Cadillac,Eldorado,Manual,Red,31500,Passenger,Greenville
3,C_CND_000004,2022-01-02,Male,13500,Toyota,Celica,Manual,Pale White,14000,SUV,Pasco
4,C_CND_000005,2022-01-02,Male,1465000,Acura,TL,Auto,Red,24500,Hatchback,Janesville
...,...,...,...,...,...,...,...,...,...,...,...
23901,C_CND_023902,2023-12-31,Male,13500,Plymouth,Voyager,Manual,Red,12000,Passenger,Pasco
23902,C_CND_023903,2023-12-31,Female,900000,Chevrolet,Prizm,Auto,Black,16000,Hardtop,Middletown
23903,C_CND_023904,2023-12-31,Male,705000,BMW,328i,Manual,Red,21000,Sedan,Scottsdale
23904,C_CND_023905,2023-12-31,Male,13500,Chevrolet,Metro,Auto,Black,31000,Passenger,Austin
23905,C_CND_023906,2023-12-31,Male,1225000,Lexus,ES300,Auto,Pale White,27500,Hardtop,Middletown

## **5Ô∏è‚É£ Standardize Text Columns**

In [268]:
# üé® Standardize string formatting
df.columns = df.columns.str.strip()
df['Gender']   = df['Gender'].str.strip().str.title()
df['Company'] = df['Company'].str.strip().str.title()
df['Model']     = df['Model'].str.strip().str.title()
df['Color']     = df['Color'].str.strip().str.title()
df['Body_Style']     = df['Body_Style'].str.strip().str.title()
df['Dealer_Region']     = df['Dealer_Region'].str.strip().str.title()

# **6Ô∏è‚É£ Validate Cleaned Data**

In [269]:
# ‚úÖ Quick sanity check
print("Final Shape:", df.shape)
print("Null Values:\n", df.isnull().sum())
df.head()

Final Shape: (23906, 11)
Null Values:
 Car_id           0
Date             0
Gender           0
Annul_Income     0
Company          0
Model            0
Transmission     0
Color            0
Price            0
Body_Style       0
Dealer_Region    0
dtype: int64

,Car_id,Date,Gender,Annul_Income,Company,Model,Transmission,Color,Price,Body_Style,Dealer_Region
0,C_CND_000001,2022-01-02,Male,13500,Ford,Expedition,Auto,Black,26000,Suv,Middletown
1,C_CND_000002,2022-01-02,Male,1480000,Dodge,Durango,Auto,Black,19000,Suv,Aurora
2,C_CND_000003,2022-01-02,Male,1035000,Cadillac,Eldorado,Manual,Red,31500,Passenger,Greenville
3,C_CND_000004,2022-01-02,Male,13500,Toyota,Celica,Manual,Pale White,14000,Suv,Pasco
4,C_CND_000005,2022-01-02,Male,1465000,Acura,Tl,Auto,Red,24500,Hatchback,Janesville

# **7Ô∏è‚É£  Save Cleaned Dataset**

In [270]:
# üíæ Save cleaned dataset
df.to_csv('Cleaned_Car_Sales_Dataset.csv', index=False)

print("‚úÖ Data cleaning complete! Cleaned file saved as 'Cleaned_Car_Sales_Dataset.csv'")

‚úÖ Data cleaning complete! Cleaned file saved as 'Cleaned_Car_Sales_Dataset.csv'